<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30836" started-at="2017-12-26T11:32:07Z" finished-at="2017-12-26T11:32:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="30836" started-at="2017-12-26T11:32:07Z" finished-at="2017-12-26T11:32:37Z">
      <class name="com.skm.mavenproject.JBK_Offline">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.skm.mavenproject.JBK_Offline@8e7350]" name="beforeMethod" is-config="true" duration-ms="16" started-at="2017-12-26T17:02:07Z" finished-at="2017-12-26T17:02:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test_Extent()[pri:0, instance:com.skm.mavenproject.JBK_Offline@8e7350]" name="test_Extent" duration-ms="25876" started-at="2017-12-26T17:02:07Z" finished-at="2017-12-26T17:02:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.skm.mavenproject.JBK_Offline.test_Extent(JBK_Offline.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Extent -->
        <test-method status="PASS" signature="test_Failure_function(org.testng.ITestResult)[pri:0, instance:com.skm.mavenproject.JBK_Offline@8e7350]" name="test_Failure_function" is-config="true" duration-ms="4882" started-at="2017-12-26T17:02:33Z" finished-at="2017-12-26T17:02:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_Extent status=FAILURE method=JBK_Offline.test_Extent()[pri:0, instance:com.skm.mavenproject.JBK_Offline@8e7350] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Failure_function -->
      </class> <!-- com.skm.mavenproject.JBK_Offline -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
